1.4/Dockerfile, 1.5/Dockerfile
haproxy 1.5 has a run time dependency on libpcre3 and therefore
the libraries should be installed independently of the build
dependencies.
=> Fix the haproxy 1.5 libpcpre3 dependency.

1.4/Dockerfile, 1.5/Dockerfile, 1.6/Dockerfile
Jessie is Debian:stable, so we should use that.
=> Bump Debian version to jessie

1.4/Dockerfile, 1.4/docker-entrypoint.sh, 1.5/Dockerfile, 1.5/docker-entrypoint.sh, 1.6/Dockerfile, 1.6/docker-entrypoint.sh
I have only tested 1.6 and only slightly.
Reload like `docker kill --signal=USR2 <container>` or HUP
Full path and pid is required for haporxy-systemd-wrapper to work.
Fix #5
=> Add reload support

.travis.yml, 1.7/Dockerfile, 1.7/alpine/Dockerfile, 1.7/alpine/docker-entrypoint.sh, 1.7/docker-entrypoint.sh
Closes docker-library/haproxy#34
```
[timwolla@/s/D/o/haproxy (1.7)]diff -Nur 1.6 1.7                                                                                                                                                            16:35:06
diff -Nur 1.6/alpine/Dockerfile 1.7/alpine/Dockerfile
--- 1.6/alpine/Dockerfile	2016-11-27 16:34:19.693358288 +0100
+++ 1.7/alpine/Dockerfile	2016-11-27 16:34:20.177366698 +0100
@@ -1,8 +1,8 @@
FROM alpine:3.4
-ENV HAPROXY_MAJOR 1.6
-ENV HAPROXY_VERSION 1.6.10
-ENV HAPROXY_MD5 6d47461c008b823a0088d19ec30dbe4e
+ENV HAPROXY_MAJOR 1.7
+ENV HAPROXY_VERSION 1.7.0
+ENV HAPROXY_MD5 ab6e169aeb1b53364aacda80c904398a
RUN set -x \
diff -Nur 1.6/Dockerfile 1.7/Dockerfile
--- 1.6/Dockerfile	2016-11-27 16:34:19.685358149 +0100
+++ 1.7/Dockerfile	2016-11-27 …
```
=> Add haproxy 1.7

1.6/Dockerfile, 1.6/alpine/Dockerfile, 1.7/Dockerfile, 1.7/alpine/Dockerfile
Following https://github.com/docker-library/haproxy/issues/28#issuecomment-268682953, there you have Lua support for 1.6+.
[It must be Lua >= 5.3, so I cannot use system packages for now](http://blog.haproxy.com/2015/10/14/whats-new-in-haproxy-1-6/). Debian and Alpine have older packaged versions.
@Tecnativa
=> Add lua support.

1.4/alpine/Dockerfile, 1.5/alpine/Dockerfile, 1.6/alpine/Dockerfile, 1.7/alpine/Dockerfile
Copying the improvement from https://github.com/docker-library/ruby/pull/161.  Should be no discernible change in packages installed, but does make the sub-shell a little easier to understand.
=> Adjust scanelf to properly detect runDeps

.travis.yml, 1.8-rc/Dockerfile, 1.8-rc/alpine/Dockerfile, 1.8-rc/alpine/docker-entrypoint.sh, 1.8-rc/docker-entrypoint.sh, generate-stackbrew-library.sh, update.sh
Closes docker-library/haproxy#48
haproxy 1.8-rc4 is the first version I found stable enough for use inside of a Docker container. This pull request implements my suggestions I made on #48:
- Switch to Debian Stretch and Alpine 3.6
- Replace systemd-wrapper by master-worker-mode (`-W`)
I verified that reloading haproxy works fine in master-worker mode.
According to [Willy on the mailing list](https://www.mail-archive.com/haproxy@formilux.org/msg27884.html) the final release is not too far off. I'm creating this pull request nonetheless for some early discussion of the changes I did.
=> Add haproxy 1.8-rc4

1.6/alpine/Dockerfile, 1.7/alpine/Dockerfile, 1.8-rc/alpine/Dockerfile
Updating the Lua version _could_ be added to the update script... but I'm lazy and Lua doesn't release new versions very often currently.
(I can also update the update script but it'll take a little while before I have the time).
=> Alpine: Update Lua to 5.3.4

1.5/Dockerfile, 1.5/alpine/Dockerfile, 1.6/Dockerfile, 1.6/alpine/Dockerfile, 1.7/Dockerfile, 1.7/alpine/Dockerfile, 1.8/Dockerfile, 1.8/alpine/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template, update.sh
Fixes #61.
`1.5` should be materially unchanged. It'll be just the swap to `wget` and the explicit install of `zlib1g-dev` which was already assumed to be installed with `USE_ZLIB=1` (it is a dependency of `libssl-dev` in jessie but not stretch).
=> Add templates and remove manual Lua install

1.5/Dockerfile, 1.5/alpine/Dockerfile, 1.6/Dockerfile, 1.6/alpine/Dockerfile, 1.7/Dockerfile, 1.7/alpine/Dockerfile, 1.8/Dockerfile, 1.8/alpine/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template
To stop haproxy gracefully, SIGUSR1 is required. Currently, we just use SIGTERM, which is a hard stop.
=> Stop with SIGUSR1

.travis.yml, 1.5/Dockerfile, 1.5/alpine/Dockerfile, 1.6/Dockerfile, 1.6/alpine/Dockerfile, 1.7/Dockerfile, 1.7/alpine/Dockerfile, 1.8/Dockerfile, 1.8/alpine/Dockerfile, 1.9/Dockerfile, 1.9/alpine/Dockerfile, 2.0-rc/Dockerfile, 2.0-rc/alpine/Dockerfile, 2.0-rc/alpine/docker-entrypoint.sh, 2.0-rc/docker-entrypoint.sh, Dockerfile-alpine.template, Dockerfile-debian.template
Final release is planned for the end of the month: https://www.mail-archive.com/haproxy@formilux.org/msg33781.html
This pull request serves as a first smoke test, I don't expect any breakage, though.
---
I'd like to point out this paragraph from #79 as well:
> It should also be evaluated whether the haproxy:1 alias makes sense. The next version will be called 2.0 while not making any breaking changes to the best of my knowledge.
We should think about dropping `haproxy:1` and `haproxy:2` aliases and instead only provide `:latest` and the various “minor” versions. HAProxy 2.1 will remove some long-deprecated configuration options, though: https://www.mail-archive.com/haproxy@formilux.org/msg33580.html
=> Add HAProxy 2.0-rc (2.0-dev3)

generate-stackbrew-library.sh
Forgot in #89. Why isn't this done by `update.sh` :unamused: :grinning:
=> Update generate-stackbrew-library.sh for 2.0

1.5/Dockerfile, 1.5/alpine/Dockerfile, 1.6/Dockerfile, 1.6/alpine/Dockerfile, 1.7/Dockerfile, 1.7/alpine/Dockerfile, 1.8/Dockerfile, 1.8/alpine/Dockerfile, 1.9/Dockerfile, 1.9/alpine/Dockerfile, 2.0/Dockerfile, 2.0/alpine/Dockerfile, Dockerfile-alpine.template, Dockerfile-debian.template
This is the last one for now, I promise!
------
The Debian package uses PCRE 2 by now and pcre.org says:
> There are two major versions of the PCRE library. The current version,
> PCRE2, first released in 2015, is now at version 10.33.
>
> The older, but still widely deployed PCRE library, originally released in
> 1997, is at version 8.43. Its API and feature set are stable—future
> releases will be for bugfixes only. Any new features will be added to
> PCRE2, and not to the PCRE 8.x series.
Note: libpcre3 in Debian is PCRE 1.
=> Switch to PCRE 2 and enable PCRE JIT

.travis.yml, 1.6/alpine/Dockerfile, 1.7/alpine/Dockerfile, 1.8/alpine/Dockerfile, 1.9/alpine/Dockerfile, 2.0/alpine/Dockerfile, 2.1/alpine/Dockerfile, 2.2-rc/Dockerfile, 2.2-rc/alpine/Dockerfile, 2.2-rc/alpine/docker-entrypoint.sh, 2.2-rc/docker-entrypoint.sh, Dockerfile-alpine.template
With 2.2-dev5 HAProxy 2.2 is nearing the end of the development cycle: https://www.mail-archive.com/haproxy@formilux.org/msg36774.html
It's a good opportunity to add prepare the Docker image. The Dockerfile is identical to the 2.1 one. 
There's one (or rather two) new Makefile option that might or might not the set: [`HLUA_PREPEND_PATH`](https://github.com/haproxy/haproxy/blob/3328f1859645ac97ce6725aa7311e6bf73aacf9c/Makefile#L87-L88) which adds a folder to the Lua search path similar to the new [`lua-prepend-path`](http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#3.1-lua-prepend-path) configuration option. I don't think it's super useful in the context of Docker, because it's a single purpose image and users can simply plug their scripts into the global Lua path, without …
=> Add HAProxy 2.2-dev5 as 2.2-rc

1.8/Dockerfile, 1.8/alpine/Dockerfile, 1.9/Dockerfile, 1.9/alpine/Dockerfile, 2.0/Dockerfile, 2.0/alpine/Dockerfile, 2.1/Dockerfile, 2.1/alpine/Dockerfile
see: https://www.mail-archive.com/haproxy@formilux.org/msg36876.html
=> [CVE-2020-11100] Update to HAProxy 2.1.4, 2.0.14, 1.9.15, 1.8.25

generate-stackbrew-library.sh
The November releases of haproxy will only be supported for one year
starting with haproxy 1.9.
-----
see the “Quick News”: https://www.haproxy.org/#news
> An important point to note, this technical release is not suitable for inclusion in distros, as it will only be maintained for approximately one year (till 2.1 is out). Version 2.0 coming in May will be long-lived and more suitable for distros.
Making latest point to `1.9` makes sense nonetheless, as it's the first with logging to stdout.
It should also be evaluated whether the `haproxy:1` alias makes sense. The next version will be called 2.0 while not making any breaking changes to the best of my knowledge.
=> Add lts / edge tag

1.7/alpine/Dockerfile, 1.8/alpine/Dockerfile, 1.9/alpine/Dockerfile, 2.0/alpine/Dockerfile, 2.1/alpine/Dockerfile, 2.2-rc/alpine/Dockerfile, Dockerfile-alpine.template
The CA bundle necessary for downloading from "https://www.haproxy.org" is already included in the base, and there's a fun bug where installing and then uninstalling the `ca-certificates` package removes what we need (see https://github.com/docker-library/haproxy/issues/117#issuecomment-645615214).
Closes #117
=> Remove "ca-certificates" package from Alpine build-deps

2.0/Dockerfile, 2.0/alpine/Dockerfile, Dockerfile-alpine.template, update.sh
(CI is going to fail to build `haproxy:2.0-alpine` in the same way it's failing at https://doi-janky.infosiftr.net/job/update.sh/job/haproxy/, but I want to get it open to have a better place to link back to in an issue at https://github.com/haproxy/haproxy/issues)
```console
...
Step 5/9 : RUN set -x 		&& apk add --no-cache --virtual .build-deps 		gcc 		libc-dev 		linux-headers 		lua5.3-dev 		make 		openssl 		openssl-dev 		pcre2-dev 		readline-dev 		tar 		zlib-dev 		&& wget -O haproxy.tar.gz "$HAPROXY_URL" 	&& echo "$HAPROXY_SHA256 *haproxy.tar.gz" | sha256sum -c 	&& mkdir -p /usr/src/haproxy 	&& tar -xzf haproxy.tar.gz -C /usr/src/haproxy --strip-components=1 	&& rm haproxy.tar.gz 		&& makeOpts=' 		TARGET=linux-glibc 		USE_GETADDRINFO=1 		USE_LUA=1 LUA_INC=/usr/include/lua5.3 …
```
=> Update to 2.0.16

2.0/alpine/Dockerfile, Dockerfile-alpine.template, update.sh
This switches us from my hanky `awk` one-liner to the actual backported patch from https://git.haproxy.org/?p=haproxy-2.0.git;a=commit;h=5df32b51bb0c3c89b503d04cd7d31bdd77932370.
Refs https://github.com/docker-library/haproxy/pull/126, https://github.com/haproxy/haproxy/issues/760
=> Apply the canonical backported ebtree patch from upstream

2.2/Dockerfile, 2.2/alpine/Dockerfile
Hi, haproxy [2.2.3 is out](https://www.haproxy.org/download/2.2/src/CHANGELOG). Here is a PR to update it, thank you!
=> chore: update to 2.2.3

2.4-rc/Dockerfile, 2.4-rc/alpine/Dockerfile
For some reason the bot did not pick this up.
=> Update to 2.4-dev13

1.7/Dockerfile, 1.7/alpine/Dockerfile, Dockerfile.template, versions.json
For some reason the bot did not pick this up.
=> Update to 1.7.13

2.4-rc/Dockerfile, 2.4-rc/alpine/Dockerfile, Dockerfile.template, versions.json
SLZ is included by default and the recommended library:
haproxy/haproxy@12840be
=> Disable ZLIB starting with HAProxy 2.4

generate-stackbrew-library.sh
This is a prerequisite of something like https://github.com/docker-library/haproxy/pull/167 to ensure users who can't update Docker for one reason or another have an escape hatch (which also means they won't update HAproxy either, but they can't have everything). :sweat_smile:
```diff
$ diff -u <(bashbrew cat haproxy) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2021-08-20 16:03:13.543529675 -0700
+++ /dev/fd/62	2021-08-20 16:03:13.543529675 -0700
@@ -1,72 +1,72 @@
Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon), Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/haproxy.git
-Tags: 2.5-dev4, 2.5-dev
+Tags: 2.5-dev4, 2.5-dev, 2.5-dev4-buster, 2.5-dev-buster
Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, …
```
=> Add suite aliases ("alpine3.14", etc)

2.2/Dockerfile, 2.3/Dockerfile, 2.4/Dockerfile, 2.5-rc/Dockerfile, versions.json, versions.sh
Older versions have not been adjusted to prefer stability. The EOL of HAProxy
2.0 nicely matches up the EOL of Debian Buster LTS and thus was choosen as the
cut-off point.
=> Update to debian:bullseye-slim for 2.2+

1.7/Dockerfile, 1.7/alpine/Dockerfile, 1.8/Dockerfile, 1.8/alpine/Dockerfile, 2.0/Dockerfile, 2.0/alpine/Dockerfile, 2.2/Dockerfile, 2.2/alpine/Dockerfile, 2.3/Dockerfile, 2.3/alpine/Dockerfile, 2.4/Dockerfile, 2.4/alpine/Dockerfile, 2.5-rc/Dockerfile, 2.5-rc/alpine/Dockerfile, Dockerfile.template
In the v2.4 `Dockerfile` user **haproxy** is added without creating a $HOME directory for it. I may miss something here, but I would like to know why is this user without a home directory? https://github.com/docker-library/haproxy/blob/caa9511cd1ae40248aaf542a2c738d745006cbe6/2.4/Dockerfile#L15
I would use the *haproxy* user's home directory for stats socket, but the dir does not exists, and as 2.4 runs as unprivileged *haproxy* user, I have no permission to create the directory( and I don't want to use `/tmp`).
Example config:
```haproxy
stats socket /var/lib/haproxy/haproxy-stats.sock
```
I can imagine that this change may raise security issues, then reject.
=> Create $HOME directory for haproxy user

generate-stackbrew-library.sh
Only moving `latest` to `2.7` since `2.6` is still the newest `lts` until the `2.8` release.
=> Bump latest to 2.7

2.0/Dockerfile, 2.0/alpine/Dockerfile, 2.2/Dockerfile, 2.2/alpine/Dockerfile, 2.4/Dockerfile, 2.4/alpine/Dockerfile, 2.5/Dockerfile, 2.5/alpine/Dockerfile, 2.6/Dockerfile, 2.6/alpine/Dockerfile, 2.7/Dockerfile, 2.7/alpine/Dockerfile, 2.8/Dockerfile, 2.8/alpine/Dockerfile, Dockerfile.template
Opted to apply this to 2.7+ only, as the odd-numbered versions are for power-users that are able to deal with some breakage.
-------------------
Resolves docker-library/haproxy#200
=> Specify WORKDIR /var/lib/haproxy

2.0/Dockerfile, 2.2/Dockerfile, 2.2/alpine/Dockerfile, 2.4/Dockerfile, 2.6/Dockerfile, 2.7/Dockerfile, 2.8/Dockerfile, 2.9/Dockerfile, 3.0/Dockerfile, Dockerfile.template, versions.json, versions.sh
Leaving `2.0` on Debian buster: https://github.com/docker-library/haproxy/pull/167
=> Update to Debian bookworm

2.9/Dockerfile, 2.9/alpine/Dockerfile, 3.0/Dockerfile, 3.0/alpine/Dockerfile, Dockerfile.template
Following @TimWolla suggestion in https://github.com/docker-library/haproxy/commit/f389054a408dd4a1cb6f314fd66a851f565190d3#r119087804:
Encouraging Lua 5.4 adoption by building newer haproxy versions with the lua5.4-dev package.
Versions prior to 2.9 will still be built with the lua5.3-dev package to prevent any breakage.
(only `Dockerfile.template` was modified, and then `./update.sh` was used to update Dockerfiles)
=> Use Lua5.4 as default version when building haproxy 2.9+

2.0/Dockerfile, 2.0/alpine/Dockerfile, 2.2/Dockerfile, 2.2/alpine/Dockerfile, 2.4/Dockerfile, 2.4/alpine/Dockerfile, 2.6/Dockerfile, 2.6/alpine/Dockerfile, 2.7/Dockerfile, 2.7/alpine/Dockerfile, 2.8/Dockerfile, 2.8/alpine/Dockerfile, 2.9/Dockerfile, 2.9/alpine/Dockerfile, 3.0/Dockerfile, 3.0/alpine/Dockerfile, Dockerfile.template
Without this package, `/etc/ssl/certs` is either empty or incomplete, and so does the `@system-ca` variable within haproxy.
This results in some haproxy client ssl features not working out of the box. For instance, using httpclient with https endpoints will not work with default config since ssl verify is on by default.
For the debian image: 
- the `ca-certificates` package was already installed as a build dependency, but all build dependencies are automatically removed during the image cleanup, so I moved it out of the build dependencies.
- As the `openssl` binary is a hard dependency for `ca-certificates` package (probably to regen/reconfigure the certs), we manually remove it during the image cleanup using `rm`.
How to test it:
- `show ssl ca-file @system-ca` haproxy cli should not …
=> Resolving missing ca-certificates dependency that causes client ssl verify to fail

2.0/Dockerfile, 2.2/Dockerfile, 2.4/Dockerfile, 2.6/Dockerfile, 2.7/Dockerfile, 2.8/Dockerfile, 2.9/Dockerfile, 3.0/Dockerfile, Dockerfile.template
See https://github.com/docker-library/python/pull/858
* Fixes #225
The issue comes from the logic that aims at removing the packages that were needed to build `haproxy` but which are not needed at runtime anymore.
```bash
find /usr/local -type f -executable -exec ldd '{}' ';' \
| awk '/=>/ { so = $(NF-1); if (index(so, "/usr/local/") == 1) { next }; gsub("^/(usr/)?", "", so); print so }' \
| sort -u \
| xargs -r dpkg-query --search \
| cut -d: -f1 \
| sort -u \
| xargs -r apt-mark manual \
```
The `ldd` looks for the libraries that `haproxy` depends on, among which, `libc.so.6`. The `awk` command reformats the output of `ldd` and produces, among other libraries:
```
lib/x86_64-linux-gnu/libc.so.6
```
Those files are then passed to `dpkg-query` to find their owning package. And this is …
=> Fix `dpkg-query --search` to be more specific

2.0/Dockerfile, 2.0/docker-entrypoint.sh, apply-templates.sh, docker-entrypoint.sh, generate-stackbrew-library.sh, versions.json, versions.sh
I thought about excluding 2.0 from conditionals in the template, etc where it's Alpine related, but 2.2 is still there and since we already worked out the logic it feels more "complete" to leave them in for now.
Also, this is `FROM debian:buster`, so it'll go away in June whether 2.0 is EOL or not.  Users should plan accordingly.
=> Restore 2.0 (not yet EOL)

Dockerfile.template, versions.sh
The end result is the same, but the construction is more ergonomic.
See also https://github.com/docker-library/buildpack-deps/pull/165 (and linked)
=> Use jq's `IN()` instead of `index()`
